package quizframework;

import quizframework.utils.CodeUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Abstract class intended to form the basis of new question types. Some methods are abstract (and need to implementations);
 * others have default implementations that you can override if you choose.
 * Questions need a title, description, data seeds (data used to generate the question, which can appear in the description),
 * a way to compute the correct answer and a way to compute incorrect answers. Optionally you can also override the number of
 * points available (this defaults to 1) and the general, correct and incorrect feedback (these default to null, which should
 * ideally be changed though Canvas does not display all of it anyway).
 * NOTE you may well first implement another abstract class, if you wish to develop several questions
 * based on the same concept - so avoiding repeating common code.
 */

public abstract class Question {

    private final QuestionData questData = new QuestionData();
    private final List<Answer> faultList = new ArrayList<>();

    /* Abstract Methods - MUST be implemented */

    /**
     * Abstract method to return a question title. A typical implementation will just return a constant string
     * @return the question title
     */
    public abstract String createQuestionTitle();

    /**
     * Abstract method to return the question description. A typical implementation will return a string with embedded
     * data used to compute the correct answer for this specific question. This data is either stored in normal
     * fields, or - optionally - stored in a HashMap of
     * {@CalcData} objects, which will be generated before this method is called.
     * @return the question description text (commonly with embedded data fields/{@CalcData} data
     */
    public abstract String createQuestionText();

    /**
     * Generate any data that will be used by the question. For example, if you want to generate a question "What is the
     * square of X?", where X is generated (and potentially different) for each use of the question, then you need to
     * generate (probably) a random integer. This can be stored in either a field, or in an object of the {@CalcData} class.
     * This method is guaranteed to be called <strong>before</strong> any others when generating a question, so the
     * data will be available when computing the correct and incorrect answers, and can also appear in te description.
     */
    public abstract void createCalcData();

    /**
     * Create and return a correct answer to the question, based on the data generated by {@createCalcData}. Typically,
     * this will include the implementation that is your solution to the problem (either directly or indirectly)
     * @return the {@Answer} object that is the correct answer to the question, based on the data generated by {@createCalcData}
     */
    public abstract Answer createCorrectAnswer();

    /**
     * Create and return an incorrect answer. This will typically be called multiple times, and incorrect answers need
     * to be unique. However, that is handled elsewhere and <strong>there is no requirement to ensure that here</strong>
     * @return an {@Answer} object that is the incorrect answer to the question.
     */
    public abstract Answer createIncorrectAnswer();

    /* Overridable Methods - CAN be implemented */

    /**
     * Return the number of points for the question. By default, this returns 1 (but can be optionally overridden)
     * @return the number of points (defaults to 1)
     */
    public int createQuestionPoints() {
        return 1;
    }

    /**
     * Return the general feedback for the question - defaults to null (which should be fixed) but can be overridden
     * @return the general feedback to the question
     */
    public String createGeneralFeedback() {
        return null;
    }

    /**
     * Return the general correct answer feedback for the question - defaults to null (which should be fixed) but can be overridden
     * @return the general correct answer feedback to the question
     */
    public String createCorrectFeedback() {
        return null;
    }

    /**
     * Return the general incorrect answer feedback for the question - defaults to null (which should be fixed) but can be overridden
     * @return the general incorrect answer feedback to the question
     */
    public String createIncorrectFeedback() {
        return null;
    }

    /**
     * Check that the answer is correctly either correct or wrong - defaults to returning true if the answer is marked correct
     * and false otherwise. Can be overridden to compute the correctness of the tested answer. The rationale is that an implementation
     * of this method should contain an example of how to solve the problem as a test and sample solution. Note this would not
     * normally be called directly but by the {@link #checkAnswerSet() checkAnswerSet} method.
     *
     * @param answer The answer being tested for correctness
     * @return true if the answer is correct, false otherwise.
     */
    public boolean checkAnswer(final Answer answer) {
        return answer.isCorrect();
    }

    /* Operational Methods - CANNOT be overridden */

    /**
     * Create a multiple choice (MCQ) question with the specified number of answers (including both correct and incorrect
     * ones). It will check to see if the correct answer is already present, defined to mean that the correct answer is already
     * present - since the correct answer is added first, and the code ensures incorrect ones are unique and do not match
     * the correct one, this should not happen. However, although this question type only has one possible correct answer, future
     * question types may have multiple correct answers.
     * @param numAnswers the number of answers (correct and incorrect) required.
     * @return true for success and false for failure (should not happen)
     */
    public final boolean createMcqAnswerSet(final int numAnswers) {
        createCalcData();//This needs to be first to ensure the data is available to compute question text and answers
        questData.addQuestionTitle(createQuestionTitle());
        questData.addQuestionText(createQuestionText());
        //Prevent questions having zero/negative points
        questData.addQuestionPoints(createQuestionPoints() < 1 ? 1 : createQuestionPoints());
        questData.addGeneralFeedback(createGeneralFeedback());
        questData.addCorrectFeedback(createCorrectFeedback());
        questData.addIncorrectAnswerFeedback(createIncorrectFeedback());
        //Add the correct answer first to ensure an incorrect one randomly-matching it is not already present
        if (!questData.addAnswer(createCorrectAnswer())) {
            return false;
        }

        //Add the required number of incorrect answers, ensuring they are unique
        final int incorrectAnswers = Math.max(1, numAnswers - 1);
        int incorrectCount = 0;
        while (incorrectCount < incorrectAnswers) {
            if (questData.addAnswer(createIncorrectAnswer())) {
                incorrectCount++;
            }
        }
        return true;
    }

    /**
     * Check the correctness of all the recorded answers by calling {@link #checkAnswer(Answer answer) checkAnswer} for
     * each one. For debugging returns a list of answers that do not match the expected result.
     * By default, checkAnswer just uses the correct/incorrect stored in each {@link Answer Answer} and so
     * will always return an empty list. Override {@link #checkAnswer(Answer answer) checkAnswer} with a sample/reference
     * implementation of the answer to the question to check it's correctness.
     *
     * @return
     */
    public final boolean checkAnswerSet() {

        for(Answer answer : questData.getAnswerList()) {
            //If checkAnswer does not agree with the recorded correctness of the answer
            if (answer.isCorrect() && !checkAnswer(answer)
            || !answer.isCorrect() && checkAnswer(answer)) {
                faultList.add(answer);
            }
        }
        return faultList.isEmpty();
    }

    /**
     * Get the list of non-matching answers based on running {@link #checkAnswerSet() checkAnswerSet} - correct answer
     * marked wrong on incorrect answers marked correct.
     *
     * @return the list of faulty answers.
     */
    public List<Answer> getFaultList() {
        return faultList;
    }

    /**
     * Used to represent the question as a readable string - <emph>provided the question is fault free</emph>.
     * The correct answer is always returend <emph>first</emph> - unlike {@link #toText2Qti(int) toText2Qti} where
     * the orders are random (this is because this method is mainly used for question checking.
     *
     * If there are faults in the question, only those answers which are not correct (do not pass the fault testing)
     * are output, with the correct answer first.
     *
     * Only meaningfully called
     * after you have called {@link #createMcqAnswerSet(int answers) createMcqAnswerSet} (or possible future methods
     * generating different question types.
     * @return the String representation of the
     */
    @Override
    public final String toString() {
        StringBuilder builder = new StringBuilder(questData.getQuestionTitle());
        builder.append("\n");
        builder.append(questData.getQuestionText());
        builder.append("\n");
        builder.append("Points: " + questData.getQuestionPoints() + "\n");

        if (!faultList.isEmpty()) {
            builder.append("QUESTION DOES NOT PASS FAULT CHECKING\n");
            builder.append("The following answers do not match the expected value:\n");
            for(Answer ans: faultList) {
                builder.append(ans.getQuestionAnswer() + " should be: " + (ans.isCorrect() ? "correct\n" : "incorrect\n"));
            }
        } else {

            List<Answer> list = questData.getAnswerList();
            for (Answer ans : list) {
                builder.append(ans.getQuestionAnswer());
                if (ans.isCorrect()) {
                    builder.append(" *");
                }
                builder.append("\n");
            }
        }

        return builder.toString();
    }

    /**
     * Generate the question test in a format suitable for text2qti (https://github.com/gpoore/text2qti). quizframework.Answer order
     * is randomized. The format is a restricted form of markDown.
     * @param qNum the number that should appear in the questions
     * @return the (markDown) format string suitable for text2qti
     */
    public final String toText2Qti(final int qNum) {
        StringBuilder builder = new StringBuilder("Title: " + questData.getQuestionTitle() + "\n");
        builder.append("Points: " + questData.getQuestionPoints() + "\n");
        builder.append(CodeUtils.outputTextBlock(qNum + ". ", questData.getQuestionText()));
        if (questData.getGeneralFeedback() != null) {
            builder.append(CodeUtils.outputTextBlock("... ", questData.getGeneralFeedback()));
        }
        if (questData.getCorrectAnswerFeedback() != null) {
            builder.append(CodeUtils.outputTextBlock("+ ", questData.getCorrectAnswerFeedback()));
        }
        if (questData.getIncorrectAnswerFeedback() != null) {
            builder.append(CodeUtils.outputTextBlock("- ", questData.getIncorrectAnswerFeedback()));
        }
        ArrayList<Answer> list = randomize();
        char qItem = 'a';
        for (Answer ans: list) {
            String qLabel = (ans.isCorrect() ? "*" : "") + qItem + ")";
            builder.append(CodeUtils.outputTextBlock(qLabel, ans.getQuestionAnswer()));
            if (ans.getFeedback() != null) {
                builder.append(CodeUtils.outputTextBlock("... ", ans.getFeedback()));
            }
            qItem++;
        }
        return builder.toString();
    }

    /* Private Methods */

    /*Shuffle an arraylist - used to randomize the order of answers in the list of possible answers (by default, in
    MCQ example, the correct answer will always be added first and will always be at the front, so this shuffles the order) */
    private ArrayList<Answer> randomize() {
        ArrayList<Answer> list = new ArrayList<>(questData.getAnswerList());
        java.util.Collections.shuffle(list);
        return list;
    }
}
