package quizframework.utils;

import java.util.Arrays;
import java.util.List;

/**
 * Useful methods and constants for generating formatted output (including code) in Markdown-format text.
 * <ul>
 *       <li>{@link #MARKDOWN_INDENT} - the standard indenting step used to format output. Also used to ident code for
 *        consistency when generated by {@link ArrayFormatter}. Minimum sensible value if 5.</li>
 *       <li>{@link #CODE_FRAMEWORK} - the standard code template used for questions to be submitted to autograder.</li>
 *       <li>{@link #outputTextBlock} - output an indented text block with a label - the label is NOT indented.</li>
 *       <li>{@link #toCodeBlock} - "wrap" a block of text (intended to be code) in a Markdown code block.</li>
 * </ul>
 */

public final class CodeUtils {

    /*
    Prevent inadvertent instantiation
     */
    private CodeUtils(){}

    /**
     * Standard indent using Markdown. Text2Qti requires markdown content to be systematically indented within questions.
     * The (minimum) size of the indent is a function of the number of questions - it needs to be minimally question number
     * plus a '.' plus a space (so e.g. 5 for up to 999 questions.)
     */
    public static final int MARKDOWN_INDENT = 5;

    /**
     * Standard framework used for (at least some of) the question types intended to be submitted to autograder
     * Requires a class name, a block of set up code - which can be anything but typically would be, say,
     * a public static array - and a return type for the method answer.
     */
    public static final String CODE_FRAMEWORK = """
                public class %s {
                %s
                    
                     public static void main(String[] args) {
                         System.out.println(answer());
                     }
                    
                     public static %s answer() {
                         /* Write your code here - it MUST *return* the answer
                         
                            Do not change any of the variables declared above or the main method - though you can add
                            other methods if you want (make sure you do not change the "signature" of answer() - autograder
                            is expecting a static method with that name and return type and no parameters).
                         
                            Make sure you use the variables declared above in your calculation and DO NOT
                            use the values themselves directly. If you do that, your code will NOT WORK
                            when you submit it to autograder.
                            
                            If you need your code to print anything out for, say, debugging - that's fine and
                            it will not affect autograder. But it is ESSENTIAL that this method - answer() - returns
                            the result of your calculation and does not just print it!
                         */
                     }
                }
                """;

    /**
     * Format a block of code suitable to be cut and pasted to answer the question and also to be used to upload
     * to autograder - format is based on {@link #CODE_FRAMEWORK}
     * @param className the name of the class to be created
     * @param codeBlock an arbitrary block of code to be inserted - usually an array, a constant of both. No checking
     *                  is done to determine if this is legal
     * @param returnType the type returned by the method the student should write.
     * @return the formatted string
     */
    public static StringBuilder questionCode(final String className,
                                             final StringBuilder codeBlock, final String returnType) {
        return  new StringBuilder(indentTextBlock(String.format(CodeUtils.CODE_FRAMEWORK, className, codeBlock, returnType)));
    }
    /**
     * Generate an appropriately-indented (by {@link #MARKDOWN_INDENT}) block of text, with an initial unindented label
     * All lines of content must be consistently indented and the label (question number or answer number) must fit
     * within that indenting (i.e. the label is *not* indented). This means that the indenting must be strictly >
     * than the length of the label (because text2qti doesn't work if there is space after the question number).
     *
     * @param label The label that appears at the start of the first line - either the question or answer number
     * @param text  List of lines of text
     * @return the indented text block
     */
    public static String outputTextBlock(final String label, final String text) {
        final StringBuilder builder = new StringBuilder();
        final List<String> textByLine = Arrays.asList(text.split("\n"));
        builder.append(label).append(" ".repeat(MARKDOWN_INDENT - label.length())).append(textByLine.get(0)).append("\n");
        textByLine.stream().skip(1).forEach(item -> builder.append(" ".repeat(MARKDOWN_INDENT)).append(item).append("\n"));
        return builder.toString();
    }

    /**
     * Indent a text block by one 'step' ({@link #MARKDOWN_INDENT} spaces)
     * @param text the block of text
     * @return the indented text
     */
    public static String indentTextBlock(final String text) {
        return indentTextBlock(text, 1);
    }

    /**
     * Indent a text block by steps multiples of {@link #MARKDOWN_INDENT} spaces
     * @param text the block of text
     * @param steps the number of steps to indent
     * @return the indented text
     */
    public static String indentTextBlock(final String text, final int steps) {
        final String[] lines = text.trim().split("\n");
        final StringBuilder builder = new StringBuilder("\n");
        for(String line : lines) {
            builder.append(" ".repeat(Math.max(0, steps * MARKDOWN_INDENT)));
            builder.append(line).append("\n");
        }
        return builder.toString();
    }

    /**
     * Encapsulate a block of text in a Markdown code block with appropriate newline characters to ensure it formats
     * correctly.
     *
     * @param code the block of code (as a StringBuilder object)
     * @return StringBuilder object "wrapping" the code in a code block
     */
    public static StringBuilder toCodeBlock(final StringBuilder code) {
        return new StringBuilder().append("\n\n```\n").append(code).append("\n```\n\n");
    }
}
