package quizframework.utils;

import java.util.Arrays;
import java.util.List;

/**
 * Useful methods and constants for generating formatted output (including code) in Markdown-format text.
 * <ul>
 *      <li>{@link #MARKDOWN_INDENT} - the standard indenting step used to format output. Also used to ident code for
 *  *     consistency when generated by {@link ArrayFormatter}. Minimum sensible value if 5.</li>
 *  *     <li>{@link #outputTextBlock} - output an indented text block with a label - the label is NOT indented.</li>
 *  *     <li>{@link #toCodeBlock} - "wrap" a block of text (intended to be code) in a Markdown code block.</li>
 * </ul>
 */

public class CodeUtils {

    /*
    Prevent inadvertant instantiation
     */
    private CodeUtils(){}

    /**
     * Standard indent using Markdown. Text2Qti requires markdown content to be systematically indented within questions.
     * The (minimum) size of the indent is a function of the number of questions - it needs to be minimally question number
     * plus a '.' plus a space (so e.g. 5 for up to 999 questions.)
     */
    public static final int MARKDOWN_INDENT = 5;

    /**
     * Generate an appropriately-indented (by MARKDOWN_INDENT) block of text, with an initial unindented label
     * All lines of content must be consistently indented and the label (question number or answer number) must fit
     * within that indenting (i.e. the label is *not* indented). This means that the indenting must be strictly >
     * than the length of the label (because text2qti doesn't work if there is space after the question number).
     *
     * @param label The label that appears at the start of the first line - either the question or answer number
     * @param text  List of lines of text
     * @return the indented text block
     */
    public static String outputTextBlock(final String label, final String text) {
        final StringBuilder builder = new StringBuilder();
        final List<String> textByLine = Arrays.asList(text.split("\n"));
        builder.append(label).append(" ".repeat(MARKDOWN_INDENT - label.length())).append(textByLine.get(0)).append("\n");
        textByLine.stream().skip(1).forEach(item -> builder.append(" ".repeat(MARKDOWN_INDENT)).append(item).append("\n"));
        return builder.toString();
    }

    /**
     * Encapsulate a block of text in a Markdown code block with appropriate newline characters to ensure it formats
     * correctly.
     *
     * @param code the block of code (as a StringBuilder object)
     * @return StringBuilder object "wrapping" the code in a code block
     */
    public static StringBuilder toCodeBlock(final StringBuilder code) {
        return new StringBuilder().append("\n\n```\n").append(code).append("\n```\n\n");
    }
}
